### ISSUE TITLE
Provide CMake build as alternative building way

### ISSUE THREAD

**Issue by Wohlstand** [LuaJIT/LuaJIT#476]
Having to deal with raw GNU Make build system isn't convenient and flexible, especially for the case you want to use different compiler, system, it's flags, or target to many other systems easily with less effort. CMake is one of most popular cross platform building systems which is widely used by many projects include various closed enterprise solutions!

### CMake will give next abilities:
- Generate build on any other building system: GNU Make, Ninja, CodeBlocks, CodeLite, Visual Studio projects of various versions, Android builds, XCode projects for various targets, etc.
- Flexible configuring with options are can be provided in the build config.
- Allows making intuitive configuring of target environment bottlenecks to auto-tune the project (set necessary macros, add / remove specific thing or workaround, etc.) to guarantee it will work here.
- Allows to generate the "trash" into absolutely any directory than in the same folder where source is placed. Traditionally it's doing manually into "build" subdirectory of the source directory, however, it's not required, and it's possible to do this in any other folder.

You can keep both building systems with no removing of existing raw GNU-Make, but give the easier way for new projects are going to use LuaJit!

**Comment by eagleivg** [comment]
You can use this: https://github.com/OpenXRay/xray-16/blob/xd_dev/Externals/luajit.cmake

**Comment by LuoJinghua** [comment]
I have added initial cmake build system tohttps://github.com/LuoJinghua/LuaJIT/tree/v2.1

**Comment by LuoJinghua** [comment]
I have added initial cmake support to my personal [repo](https://github.com/LuoJinghua/LuaJIT/tree/v2.1). It builds on macOS/Android/Linux at least.

**Comment by sonoro1234** [comment]
Another way is to wrap already existing makefiles in ExtenalProject as in https://github.com/sonoro1234/Lua2SC/tree/master/LuaJIT

**Comment by Wohlstand** [comment]
> Another way is to wrap already existing makefiles in ExtenalProject as in https://github.com/sonoro1234/Lua2SC/tree/master/LuaJIT

That I have already made: https://github.com/WohlSoft/PGE-Project/blob/master/_common/library_luajit.cmake
However, it's a mess, especially it's hard to manage through different platforms

> I have added initial cmake support to my personal repo. It builds on macOS/Android/Linux at least.

Neat! I testing the Windows build on my VM, and MSVC failed, but MinGW failed because of CMake's:
```
CMake Error at src/CMakeLists.txt:355 (target_compile_definitions):
  target_compile_definitions called with invalid arguments
```

**Comment by Wohlstand** [comment]
But, it was configured successfully when I have replaced line with
```
target_compile_options(libluajit PRIVATE -march=i686 -msse -msse2 -mfpmath=sse)
```
However, using "ExternalProject" you'll also need to pass some flags... Because it was built with MSVC and failed....

**Comment by Wohlstand** [comment]
I have made an attempt to fix:
```cmake
add_custom_command(OUTPUT ${MINILUA_PATH}
  COMMAND ${CMAKE_COMMAND}
          -G "${CMAKE_GENERATOR}"
          "${CMAKE_CURRENT_SOURCE_DIR}/host/cmake/minilua"
          "-DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}"
          "-DCMAKE_INSTALL_PREFIX=${DEPENDENCIES_INSTALL_DIR}"
          "-DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}"
  COMMAND ${CMAKE_COMMAND} --build ${CMAKE_CURRENT_BINARY_DIR}/minilua
  WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/minilua)

add_custom_target(MINILUA_BUILD ALL
  DEPENDS ${MINILUA_PATH}
)
```
and
```cmake
add_custom_command(OUTPUT ${BUILDVM_PATH}
  COMMAND ${CMAKE_COMMAND}
          -G "${CMAKE_GENERATOR}"
          "${CMAKE_CURRENT_SOURCE_DIR}/host/cmake/buildvm"
		  "-DEXTRA_COMPILER_FLAGS_FILE=${BUILDVM_COMPILER_FLAGS_PATH}"
		  "-DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}"
          "-DCMAKE_INSTALL_PREFIX=${DEPENDENCIES_INSTALL_DIR}"
          "-DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}"
  COMMAND ${CMAKE_COMMAND} --build ${CMAKE_CURRENT_BINARY_DIR}/buildvm
  DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/host/cmake/buildvm/CMakeLists.txt
  DEPENDS BUILDVM_ARCH_H_BUILD
  WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/buildvm)
```
But still fail because of another reason:

```
C:\Users\Admin\Repos\LuaJIT\build>cmake -G "MinGW Makefiles" ..
-- The C compiler identification is GNU 5.3.0
-- The CXX compiler identification is GNU 5.3.0
-- Check for working C compiler: C:/Qt/Tools/mingw530_32/bin/gcc.exe
-- Check for working C compiler: C:/Qt/Tools/mingw530_32/bin/gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Qt/Tools/mingw530_32/bin/g++.exe
-- Check for working CXX compiler: C:/Qt/Tools/mingw530_32/bin/g++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The ASM compiler identification is GNU
-- Found assembler: C:/Qt/Tools/mingw530_32/bin/gcc.exe
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- Performing Test NO_STACK_PROTECTOR_FLAG
-- Performing Test NO_STACK_PROTECTOR_FLAG - Success
-- Check target system architecture: x86
-- Check target fpu: FPU IS Hard
-- Check target fpu abi: FPU ABI IS Hard
-- FPU: Hard FPU ABI: Hard
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/Admin/Repos/LuaJIT/build

C:\Users\Admin\Repos\LuaJIT\build>mingw32-make -j 4
Scanning dependencies of target BUILDVM_ARCH_H_BUILDScanning dependencies of tar
get MINILUA_BUILD

Scanning dependencies of target LJ_VM_S_BUILD
[  1%] Generating minilua/minilua.exe[  2%]
Generating minilua/minilua.exe
[  2%] Built target LJ_VM_S_BUILD
-- The C compiler identification is GNU 5.3.0
-- The C compiler identification is GNU 5.3.0
-- The CXX compiler identification is GNU 5.3.0
-- Check for working C compiler: C:/Qt/Tools/mingw530_32/bin/gcc.exe
-- The CXX compiler identification is GNU 5.3.0
-- Check for working C compiler: C:/Qt/Tools/mingw530_32/bin/gcc.exe
-- Check for working C compiler: C:/Qt/Tools/mingw530_32/bin/gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Check for working C compiler: C:/Qt/Tools/mingw530_32/bin/gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compile features - failed
-- Check for working CXX compiler: C:/Qt/Tools/mingw530_32/bin/g++.exe
-- Check for working CXX compiler: C:/Qt/Tools/mingw530_32/bin/g++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting C compiler ABI info - done
-- Detecting CXX compile features - failed
CMake Error: The following variables are used in this project, but they are set
to NOTFOUND.
-- Detecting C compile features
Please set them or make sure they are set and tested correctly in the CMake file
s:
LIBM
    linked by target "minilua" in directory C:/Users/Admin/Repos/LuaJIT/src/host
/cmake/minilua

-- Configuring incomplete, errors occurred!
See also "C:/Users/Admin/Repos/LuaJIT/build/src/minilua/CMakeFiles/CMakeOutput.l
og".
See also "C:/Users/Admin/Repos/LuaJIT/build/src/minilua/CMakeFiles/CMakeError.lo
g".
src\CMakeFiles\MINILUA_BUILD.dir\build.make:59: recipe for target 'src/minilua/m
inilua.exe' failed
mingw32-make[2]: *** [src/minilua/minilua.exe] Error 1
CMakeFiles\Makefile2:98: recipe for target 'src/CMakeFiles/MINILUA_BUILD.dir/all
' failed
mingw32-make[1]: *** [src/CMakeFiles/MINILUA_BUILD.dir/all] Error 2
mingw32-make[1]: *** Waiting for unfinished jobs....
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Qt/Tools/mingw530_32/bin/g++.exe
-- Check for working CXX compiler: C:/Qt/Tools/mingw530_32/bin/g++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error: The following variables are used in this project, but they are set
to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake file
s:
LIBM
    linked by target "minilua" in directory C:/Users/Admin/Repos/LuaJIT/src/host
/cmake/minilua

-- Configuring incomplete, errors occurred!
See also "C:/Users/Admin/Repos/LuaJIT/build/src/minilua/CMakeFiles/CMakeOutput.l
og".
See also "C:/Users/Admin/Repos/LuaJIT/build/src/minilua/CMakeFiles/CMakeError.lo
g".
src\CMakeFiles\BUILDVM_ARCH_H_BUILD.dir\build.make:63: recipe for target 'src/mi
nilua/minilua.exe' failed
mingw32-make[2]: *** [src/minilua/minilua.exe] Error 1
CMakeFiles\Makefile2:172: recipe for target 'src/CMakeFiles/BUILDVM_ARCH_H_BUILD
.dir/all' failed
mingw32-make[1]: *** [src/CMakeFiles/BUILDVM_ARCH_H_BUILD.dir/all] Error 2
Makefile:128: recipe for target 'all' failed
mingw32-make: *** [all] Error 2

C:\Users\Admin\Repos\LuaJIT\build>
```

**Comment by LuoJinghua** [comment]
> But still fail because of another reason. I'll try later. Otherwise, I'm at my job and I have the task to do...



> I have made an attempt to fix:
> 
> ```cmake
> add_custom_command(OUTPUT ${MINILUA_PATH}
>   COMMAND ${CMAKE_COMMAND}
>           -G "${CMAKE_GENERATOR}"
>           "${CMAKE_CURRENT_SOURCE_DIR}/host/cmake/minilua"
>           "-DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}"
>           "-DCMAKE_INSTALL_PREFIX=${DEPENDENCIES_INSTALL_DIR}"
>           "-DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}"
>   COMMAND ${CMAKE_COMMAND} --build ${CMAKE_CURRENT_BINARY_DIR}/minilua
>   WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/minilua)
> 

I just pushed some fixes to my repo, it should work much better now.

**Comment by Wohlstand** [comment]
Will try that once I'll reach my home...

**Comment by Wohlstand** [comment]
Okay, one thing you need to fix:
```cmake
if("${LJ_TARGET_ARCH}" STREQUAL "x86")
  if (CMAKE_COMPILER_IS_CLANGXX OR CMAKE_COMPILER_IS_GNUCXX)
    target_compile_options(libluajit PRIVATE -march=i686 -msse -msse2 -mfpmath=sse)
  endif()
endif()
```
Otherwise:
```
CMake Error at src/CMakeLists.txt:382 (target_compile_definitions):
  target_compile_definitions called with invalid arguments

-- Configuring incomplete, errors occurred!
See also "C:/Repos/LuaJIT/build/CMakeFiles/CMakeOutput.log".
```

And also, it still fails at me:
```
C:\Repos\LuaJIT\build>cmake -G "MinGW Makefiles" ..
-- The C compiler identification is GNU 5.3.0
-- The CXX compiler identification is GNU 5.3.0
-- Check for working C compiler: C:/Qt/Tools/mingw530_32/bin/gcc.exe
-- Check for working C compiler: C:/Qt/Tools/mingw530_32/bin/gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Qt/Tools/mingw530_32/bin/g++.exe
-- Check for working CXX compiler: C:/Qt/Tools/mingw530_32/bin/g++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The ASM compiler identification is GNU
-- Found assembler: C:/Qt/Tools/mingw530_32/bin/gcc.exe
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- Performing Test NO_STACK_PROTECTOR_FLAG
-- Performing Test NO_STACK_PROTECTOR_FLAG - Success
-- Check target system architecture: x86
-- Check target fpu: FPU IS Hard
-- Check target fpu abi: FPU ABI IS Hard
-- FPU: Hard FPU ABI: Hard
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Repos/LuaJIT/build

C:\Repos\LuaJIT\build>mingw32-make -j 4
Scanning dependencies of target LJ_VM_S_BUILDScanning dependencies of target min
ilua

[  1%] [  1%] Built target LJ_VM_S_BUILD
Building C object src/host/cmake/minilua/CMakeFiles/minilua.dir/__/__/minilua.c.
obj
[  2%] Linking C executable minilua.exe
[  2%] Built target minilua
Scanning dependencies of target buildvm_arch_h
[  3%] Generating buildvm_arch.h
[  3%] Built target buildvm_arch_h
Scanning dependencies of target buildvm
[  4%] Building C object src/host/cmake/buildvm/CMakeFiles/buildvm.dir/__/__/bui
ldvm.c.obj
[  6%] Building C object src/host/cmake/buildvm/CMakeFiles/buildvm.dir/__/__/bui
ldvm_asm.c.obj
[  7%] Building C object src/host/cmake/buildvm/CMakeFiles/buildvm.dir/__/__/bui
ldvm_fold.c.obj
[  8%] Building C object src/host/cmake/buildvm/CMakeFiles/buildvm.dir/__/__/bui
ldvm_lib.c.obj
[  9%] Building C object src/host/cmake/buildvm/CMakeFiles/buildvm.dir/__/__/bui
ldvm_peobj.c.obj
[ 11%] Linking C executable buildvm.exe
[ 11%] Built target buildvm
Scanning dependencies of target LJ_FOLDDEF_BUILDScanning dependencies of target
LJ_DEF_BUILD

mingw32-make[2]: *** No rule to make target 'src/lj_bcdef.h', needed by 'src/CMa
keFiles/LJ_DEF_BUILD'.  Stop.
mingw32-make[2]: *** Waiting for unfinished jobs....
[ 12%] Generating lj_libdef.h, jit/vmdef.lua, lj_recdef.h, lj_ffdef.h
[ 13%] Generating lj_folddef.h
CMakeFiles\Makefile2:173: recipe for target 'src/CMakeFiles/LJ_DEF_BUILD.dir/all
' failed
mingw32-make[1]: *** [src/CMakeFiles/LJ_DEF_BUILD.dir/all] Error 2
mingw32-make[1]: *** Waiting for unfinished jobs....
[ 13%] Built target LJ_FOLDDEF_BUILD
Makefile:128: recipe for target 'all' failed
mingw32-make: *** [all] Error 2

C:\Repos\LuaJIT\build>
```

**Comment by LuoJinghua** [comment]
> Okay, one thing you need to fix:
> 
> ```cmake
> if("${LJ_TARGET_ARCH}" STREQUAL "x86")
>   if (CMAKE_COMPILER_IS_CLANGXX OR CMAKE_COMPILER_IS_GNUCXX)
>     target_compile_options(libluajit PRIVATE -march=i686 -msse -msse2 -mfpmath=sse)
>   endif()
> endif()
> ```
> 
> Otherwise:
> 
> ```
> CMake Error at src/CMakeLists.txt:382 (target_compile_definitions):
>   target_compile_definitions called with invalid arguments
> 
> -- Configuring incomplete, errors occurred!
> See also "C:/Repos/LuaJIT/build/CMakeFiles/CMakeOutput.log".
> ```

Fixed now.

> And also, it still fails at me:
> 
> ```
> C:\Repos\LuaJIT\build>cmake -G "MinGW Makefiles" ..
> -- The C compiler identification is GNU 5.3.0
> -- The CXX compiler identification is GNU 5.3.0
> -- Check for working C compiler: C:/Qt/Tools/mingw530_32/bin/gcc.exe
> -- Check for working C compiler: C:/Qt/Tools/mingw530_32/bin/gcc.exe -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: C:/Qt/Tools/mingw530_32/bin/g++.exe
> -- Check for working CXX compiler: C:/Qt/Tools/mingw530_32/bin/g++.exe -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- The ASM compiler identification is GNU
> -- Found assembler: C:/Qt/Tools/mingw530_32/bin/gcc.exe
> -- Check if the system is big endian
> -- Searching 16 bit integer
> -- Looking for sys/types.h
> -- Looking for sys/types.h - found
> -- Looking for stdint.h
> -- Looking for stdint.h - found
> -- Looking for stddef.h
> -- Looking for stddef.h - found
> -- Check size of unsigned short
> -- Check size of unsigned short - done
> -- Using unsigned short
> -- Check if the system is big endian - little endian
> -- Performing Test NO_STACK_PROTECTOR_FLAG
> -- Performing Test NO_STACK_PROTECTOR_FLAG - Success
> -- Check target system architecture: x86
> -- Check target fpu: FPU IS Hard
> -- Check target fpu abi: FPU ABI IS Hard
> -- FPU: Hard FPU ABI: Hard
> -- Configuring done
> -- Generating done
> -- Build files have been written to: C:/Repos/LuaJIT/build
> 
> C:\Repos\LuaJIT\build>mingw32-make -j 4
> Scanning dependencies of target LJ_VM_S_BUILDScanning dependencies of target min
> ilua
> 
> [  1%] [  1%] Built target LJ_VM_S_BUILD
> Building C object src/host/cmake/minilua/CMakeFiles/minilua.dir/__/__/minilua.c.
> obj
> [  2%] Linking C executable minilua.exe
> [  2%] Built target minilua
> Scanning dependencies of target buildvm_arch_h
> [  3%] Generating buildvm_arch.h
> [  3%] Built target buildvm_arch_h
> Scanning dependencies of target buildvm
> [  4%] Building C object src/host/cmake/buildvm/CMakeFiles/buildvm.dir/__/__/bui
> ldvm.c.obj
> [  6%] Building C object src/host/cmake/buildvm/CMakeFiles/buildvm.dir/__/__/bui
> ldvm_asm.c.obj
> [  7%] Building C object src/host/cmake/buildvm/CMakeFiles/buildvm.dir/__/__/bui
> ldvm_fold.c.obj
> [  8%] Building C object src/host/cmake/buildvm/CMakeFiles/buildvm.dir/__/__/bui
> ldvm_lib.c.obj
> [  9%] Building C object src/host/cmake/buildvm/CMakeFiles/buildvm.dir/__/__/bui
> ldvm_peobj.c.obj
> [ 11%] Linking C executable buildvm.exe
> [ 11%] Built target buildvm
> Scanning dependencies of target LJ_FOLDDEF_BUILDScanning dependencies of target
> LJ_DEF_BUILD
> 
> mingw32-make[2]: *** No rule to make target 'src/lj_bcdef.h', needed by 'src/CMa
> keFiles/LJ_DEF_BUILD'.  Stop.
> mingw32-make[2]: *** Waiting for unfinished jobs....
> [ 12%] Generating lj_libdef.h, jit/vmdef.lua, lj_recdef.h, lj_ffdef.h
> [ 13%] Generating lj_folddef.h
> CMakeFiles\Makefile2:173: recipe for target 'src/CMakeFiles/LJ_DEF_BUILD.dir/all
> ' failed
> mingw32-make[1]: *** [src/CMakeFiles/LJ_DEF_BUILD.dir/all] Error 2
> mingw32-make[1]: *** Waiting for unfinished jobs....
> [ 13%] Built target LJ_FOLDDEF_BUILD
> Makefile:128: recipe for target 'all' failed
> mingw32-make: *** [all] Error 2
> 
> C:\Repos\LuaJIT\build>
> ```

I finally booted to windows and fixed some win32 specific issues. It builds now with mingw and visual studio 2017.

**Comment by Wohlstand** [comment]
Okay, now it works!
However, I have found a thing that happens (happens on both Linux and Windows):
- When I compiling with `-j 4`, it fails:
```
wohlstand@wohlstand-dssl ~/_git_repos/LuaJIT/build $ make -j 4
Scanning dependencies of target LJ_VM_S_BUILD
Scanning dependencies of target minilua
[  0%] Built target LJ_VM_S_BUILD
[  1%] Building C object src/host/cmake/minilua/CMakeFiles/minilua.dir/__/__/minilua.c.o
[  2%] Linking C executable minilua
[  2%] Built target minilua
Scanning dependencies of target buildvm_arch_h
[  3%] Generating buildvm_arch.h
[  3%] Built target buildvm_arch_h
Scanning dependencies of target buildvm
[  8%] Building C object src/host/cmake/buildvm/CMakeFiles/buildvm.dir/__/__/buildvm.c.o
[  8%] Building C object src/host/cmake/buildvm/CMakeFiles/buildvm.dir/__/__/buildvm_asm.c.o
[  8%] Building C object src/host/cmake/buildvm/CMakeFiles/buildvm.dir/__/__/buildvm_lib.c.o
[  8%] Building C object src/host/cmake/buildvm/CMakeFiles/buildvm.dir/__/__/buildvm_fold.c.o
[  9%] Building C object src/host/cmake/buildvm/CMakeFiles/buildvm.dir/__/__/buildvm_peobj.c.o
[ 11%] Linking C executable buildvm
[ 11%] Built target buildvm
Scanning dependencies of target LJ_FOLDDEF_BUILD
Scanning dependencies of target LJ_DEF_BUILD
make[2]: *** Нет правила для сборки цели «src/lj_bcdef.h», требуемой для «src/CMakeFiles/LJ_DEF_BUILD».  Останов.
make[2]: *** Ожидание завершения заданий…
[ 13%] Generating lj_libdef.h, jit/vmdef.lua, lj_recdef.h, lj_ffdef.h
[ 13%] Generating lj_folddef.h
CMakeFiles/Makefile2:211: recipe for target 'src/CMakeFiles/LJ_DEF_BUILD.dir/all' failed
make[1]: *** [src/CMakeFiles/LJ_DEF_BUILD.dir/all] Error 2
make[1]: *** Ожидание завершения заданий…
[ 13%] Built target LJ_FOLDDEF_BUILD
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```
But, when re-running `make -j 4` again: it gets be successfully built! So, looks like you forgot to set dependencies?
Also, it won't be built with Ninja:
```
wohlstand@wohlstand-dssl ~/_git_repos/LuaJIT/build $ cmake -G Ninja -DCMAKE_INSTALL_PREFIX=kek ..
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Check if the system is big endian
-- Searching 16 bit integer
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Using unsigned short
-- Check if the system is big endian - little endian
-- Performing Test NO_STACK_PROTECTOR_FLAG
-- Performing Test NO_STACK_PROTECTOR_FLAG - Success
-- Check target system architecture: x86_64
-- Check target fpu: FPU IS Hard
-- Check target fpu abi: FPU ABI IS Hard
-- FPU: Hard FPU ABI: Hard
-- Configuring done
-- Generating done
-- Build files have been written to: /home/wohlstand/_git_repos/LuaJIT/build
wohlstand@wohlstand-dssl ~/_git_repos/LuaJIT/build $ cmake --build . --target all
ninja: error: 'src/lj_bcdef.h', needed by 'src/CMakeFiles/LJ_DEF_BUILD', missing and no known rule to make it
wohlstand@wohlstand-dssl ~/_git_repos/LuaJIT/build $ 
```

I know this issue, and it's the solution: you need a workaround:
```cmake
# Workaround for Ninja
if(NOT EXISTS "${LJ_BCDEF_PATH}")
    file(WRITE "${LJ_BCDEF_PATH}" "dummy")
endif()
```
![default](https://user-images.githubusercontent.com/6751442/53860466-3415f300-3ff2-11e9-807e-d3f8072a654c.png)

**Comment by Wohlstand** [comment]
Okay, just now I have found I am totally unneeded for a workaround, the TRUE solution is appending of missing `${LJ_BCDEF_PATH}` into end of line 277:
```cmake
  OUTPUT ${LJ_LIBDEF_PATH} ${LJ_VMDEF_PATH} ${LJ_RECDEF_PATH} ${LJ_FFDEF_PATH}
```

![2019-03-06 09-33-04](https://user-images.githubusercontent.com/6751442/53860698-e8b01480-3ff2-11e9-989b-26559ad133f5.png)

After that both Ninja and GNU Make building successfully!

**Comment by LuoJinghua** [comment]
> Okay, just now I have found I am totally unneeded for a workaround, the TRUE solution is appending of missing `${LJ_BCDEF_PATH}` into end of line 277:
> 
> ```cmake
>   OUTPUT ${LJ_LIBDEF_PATH} ${LJ_VMDEF_PATH} ${LJ_RECDEF_PATH} ${LJ_FFDEF_PATH} ${LJ_BCDEF_PATH}
> ```
> 

Oh yeah, you nailed it.

**Comment by Wohlstand** [comment]
Tested just now everywhere on Linux and Windows, works fine! :fox_face: :+1: 
In evening at my home will try out macOS and Android builds, and then will try their working in my game engine...

**Comment by Wohlstand** [comment]
Okay, I have successfully applied my `enforce UTF8 paths` patch here:
https://github.com/WohlSoft/LuaJIT/tree/v2.1
And looks it works, but didn't done real test of build yet.

**Comment by Wohlstand** [comment]
Just now I have tested the runtime: it works fine on Linux desktop and Android!
Okay, macOS I'll test later as I'm very tired now... Finally, it was built on modern Android! Thank you @LuoJinghua for a work!
So, it's need to test something also to be sure it's fine, then make a pull-request.

**Comment by LuoJinghua** [comment]
My branch builds ok with following combinations:
* x86_64 clang on macOS
* x86_64 gcc on Linux
* mipsel gcc on Linux
* armeabi-v7a/arm64-v8a clang/gcc on Android
* mingw/visual studio on Windows

**Comment by Wohlstand** [comment]
Just now I have tested the build on macOS, and my little suggestion: don't compile sources are has no objects until they are needed, otherwise, macOS's clang will cry next:
![_2019-03-07_23-03-39](https://user-images.githubusercontent.com/6751442/53985652-447eb880-412d-11e9-9b78-8f04a178f84a.png)

**Comment by Wohlstand** [comment]
I think, there are also two-three platforms I can test this: OpenBSD, FreeBSD, and Haiku!
Will try that at evening if I'll don't be tired...

**Comment by LuoJinghua** [comment]
> I think, there are also two-three platforms I can test this: OpenBSD, FreeBSD, and Haiku!
> Will try that at evening if I'll be not tired...

It would be great if you could test these platforms. I think we need some fixes to get LuaJIT to build on these platforms.

**Comment by Wohlstand** [comment]
Okay, at first time I did the test on OpenBSD x64, and I have build that failed:
```
[ 14%] Building C object src/CMakeFiles/libluajit.dir/lj_mcode.c.o
/home/admin/repos/LuaJit/src/lj_mcode.c:123:2: error: "Missing OS support for explicit placement
      of executable memory"
#error "Missing OS support for explicit placement of executable memory"
 ^
/home/admin/repos/LuaJit/src/lj_mcode.c:197:21: warning: implicit declaration of function
      'mcode_setprot' is invalid in C99 [-Wimplicit-function-declaration]
    if (LJ_UNLIKELY(mcode_setprot(J->mcarea, J->szmcarea, prot)))
                    ^
/home/admin/repos/LuaJit/src/lj_mcode.c:236:17: warning: implicit declaration of function
      'mcode_alloc_at' is invalid in C99 [-Wimplicit-function-declaration]
      void *p = mcode_alloc_at(J, hint, sz, MCPROT_GEN);
                ^
/home/admin/repos/LuaJit/src/lj_mcode.c:236:45: error: use of undeclared identifier 'MCPROT_RW'
      void *p = mcode_alloc_at(J, hint, sz, MCPROT_GEN);
                                            ^
/home/admin/repos/LuaJit/src/lj_mcode.c:179:20: note: expanded from macro 'MCPROT_GEN'
#define MCPROT_GEN      MCPROT_RW
                        ^
/home/admin/repos/LuaJit/src/lj_mcode.c:241:14: warning: implicit declaration of function
      'mcode_free' is invalid in C99 [-Wimplicit-function-declaration]
      if (p) mcode_free(J, p, sz);  /* Free badly placed area. */
             ^
/home/admin/repos/LuaJit/src/lj_mcode.c:283:15: error: use of undeclared identifier 'MCPROT_RW'
  J->mcprot = MCPROT_GEN;
              ^
/home/admin/repos/LuaJit/src/lj_mcode.c:179:20: note: expanded from macro 'MCPROT_GEN'
#define MCPROT_GEN      MCPROT_RW
                        ^
/home/admin/repos/LuaJit/src/lj_mcode.c:312:22: error: use of undeclared identifier 'MCPROT_RW'
    mcode_protect(J, MCPROT_GEN);
                     ^
/home/admin/repos/LuaJit/src/lj_mcode.c:179:20: note: expanded from macro 'MCPROT_GEN'
#define MCPROT_GEN      MCPROT_RW
                        ^
/home/admin/repos/LuaJit/src/lj_mcode.c:321:20: error: use of undeclared identifier 'MCPROT_RX'
  mcode_protect(J, MCPROT_RUN);
                   ^
/home/admin/repos/LuaJit/src/lj_mcode.c:180:20: note: expanded from macro 'MCPROT_RUN'
#define MCPROT_RUN      MCPROT_RX
                        ^
/home/admin/repos/LuaJit/src/lj_mcode.c:328:22: error: use of undeclared identifier 'MCPROT_RX'
    mcode_protect(J, MCPROT_RUN);
                     ^
/home/admin/repos/LuaJit/src/lj_mcode.c:180:20: note: expanded from macro 'MCPROT_RUN'
#define MCPROT_RUN      MCPROT_RX
                        ^
/home/admin/repos/LuaJit/src/lj_mcode.c:340:24: error: use of undeclared identifier 'MCPROT_RX'
      mcode_protect(J, MCPROT_RUN);
                       ^
/home/admin/repos/LuaJit/src/lj_mcode.c:180:20: note: expanded from macro 'MCPROT_RUN'
#define MCPROT_RUN      MCPROT_RX
                        ^
/home/admin/repos/LuaJit/src/lj_mcode.c:341:68: error: use of undeclared identifier 'MCPROT_RX'
    else if (LJ_UNLIKELY(mcode_setprot(ptr, ((MCLink *)ptr)->size, MCPROT_RUN)))
                                                                   ^
/home/admin/repos/LuaJit/src/lj_mcode.c:180:20: note: expanded from macro 'MCPROT_RUN'
#define MCPROT_RUN      MCPROT_RX
                        ^
/home/admin/repos/LuaJit/src/lj_mcode.c:348:24: error: use of undeclared identifier 'MCPROT_RW'
      mcode_protect(J, MCPROT_GEN);
                       ^
/home/admin/repos/LuaJit/src/lj_mcode.c:179:20: note: expanded from macro 'MCPROT_GEN'
#define MCPROT_GEN      MCPROT_RW
                        ^
/home/admin/repos/LuaJit/src/lj_mcode.c:356:58: error: use of undeclared identifier 'MCPROT_RW'
        if (LJ_UNLIKELY(mcode_setprot(mc, ((MCLink *)mc)->size, MCPROT_GEN)))
                                                                ^
/home/admin/repos/LuaJit/src/lj_mcode.c:179:20: note: expanded from macro 'MCPROT_GEN'
#define MCPROT_GEN      MCPROT_RW
                        ^
3 warnings and 10 errors generated.
*** Error 1 in . (src/CMakeFiles/libluajit.dir/build.make:1027 'src/CMakeFiles/libluajit.dir/lj_mcode.c.o': cd /home/admin/repos/LuaJit/buil...)
*** Error 1 in . (CMakeFiles/Makefile2:252 'src/CMakeFiles/libluajit.dir/all')
*** Error 1 in /home/admin/repos/LuaJit/build (Makefile:130 'all')
```

I guess, it must set the POSIX mode, however, it wasn't worked, and, instead, it was faied:

```
$ clang --version
OpenBSD clang version 4.0.0 (tags/RELEASE_400/final) (based on LLVM 4.0.0)
Target: amd64-unknown-openbsd6.2
Thread model: posix
InstalledDir: /usr/bin

$ cmake --version
cmake version 3.9.3

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

**Comment by Wohlstand** [comment]
P.S. Even vanilla Makefile was failed on OpenBSD even worse (one of reasons WHY CMake is needed):
```
$ make
*** Parse error in /home/admin/repos/LuaJit: Need an operator in '/usr/local' (Makefile:28)
*** Parse error: Need an operator in 'lib' (Makefile:29)
*** Parse error: Missing dependency operator (Makefile:93)
*** Parse error: Need an operator in 'else' (Makefile:95)
*** Parse error: Need an operator in 'endif' (Makefile:97)
*** Parse error: Missing dependency operator (Makefile:100)
*** Parse error: Need an operator in 'endif' (Makefile:105)
```

**Comment by Wohlstand** [comment]
For easier analysis, I uploading the build cache with all files, you can see what CMake have found inside environment
[luajit-cmake-cache.zip](https://github.com/LuaJIT/LuaJIT/files/2970525/luajit-cmake-cache.zip)

**Comment by Wohlstand** [comment]
Tested on Haiku just now: the same build error was happen, however, I'll try to fix that...

**Comment by Wohlstand** [comment]
Okay, the Haiku has been fixed: https://github.com/WohlSoft/LuaJIT/commit/29219155c61e8621d3931a97b2be5080fceb4867
Will check out xBSD builds...

**Comment by Wohlstand** [comment]
OpenBSD also has been fixed: https://github.com/WohlSoft/LuaJIT/commit/753f680cab42c63607a2ec0560705f9f8d3ace7d
With only few warnings are still:
```
CMakeFiles/buildvm.dir/__/__/buildvm.c.o: In function `sym_decorate':
/home/admin/repos/LuaJit/src/host/buildvm.c:(.text+0x36d1): warning: warning: strcpy() is almost always misused, please use strlcpy()
/home/admin/repos/LuaJit/src/host/buildvm.c:(.text+0x3669): warning: warning: sprintf() is often misused, please use snprintf()

libluajit.a(lib_os.c.o): In function `lj_cf_os_tmpname':
/home/admin/repos/LuaJit/src/lib_os.c:(.text+0x1af): warning: warning: strcpy() is almost always misused, please use strlcpy()
```

**Comment by MikePall** [comment]
The build system works fine. This project doesn't need another one.

Also CMake is an abomination. It creates more problems than it solves.
