### ISSUE TITLE
Add support for Windows/ARM64

### ISSUE THREAD

**Issue by be5invis** [LuaJIT/LuaJIT#593]
I am trying to [port NeoVim to Windows/Arm64](https://github.com/neovim/neovim/issues/12521) and currently the blocker is LuaJIT. It looks like LuaJIT has fully supported ARM64 processor but not this OS-Arch combination. Since I am using MSVC (MinGW cannot target WoA) do we have cross compilation support under MSVC now? If so what is the best practice of doing that?

**Comment by MikePall** [comment]
The target vs. OS dependencies are untangled, so in principle this ought to work.

The standard Makefile would probably already work with MinGW ... if only it had an ARM64 cross-compiler.

I'm sure one could create a variant of the msvcbuild.bat to do cross-compilation with MSVC, like the xb1build.bat does for the Xbox One. Since I don't have the required test environment, somebody else needs to contribute that.

**Comment by be5invis** [comment]
Current holes I observed:

 * The PE code generator should be modified to support ARM64;
 * ARM64 SEH needs to be implemented;
 * Fixing the building system to allow cross compilation.

CC @imbushuo

**Comment by MikuAuahDark** [comment]
Hello, I'm trying to get my hands on compiling LuaJIT for Windows 10 ARM64 (WoA) by modifying `msvcbuild.bat` with:

* Changing `vm_x64.dasc` to `vm_arm64.dasc`.
* Adding `/DLUAJIT_NUMMODE=2 /DLUAJIT_TARGET=LUAJIT_ARCH_arm64` compile flags when compiling buildvm.

I'm not sure that's enough change, however my main issue is this first two error message.
```
C:\Users\MikuAuahDark\personal-lua-stuff\LuaJIT\src\lj_jit.h(427): error C2229: struct 'jit_State' has an illegal zero-sized array
C:\Users\MikuAuahDark\personal-lua-stuff\LuaJIT\src\lj_jit.h(429): error C2229: struct 'jit_State' has an illegal zero-sized array
.\../dynasm/dasm_arm64.h(191): warning C4146: unary minus operator applied to unsigned type, result still unsigned
.\../dynasm/dasm_arm64.h(191): warning C4146: unary minus operator applied to unsigned type, result still unsigned
.\../dynasm/dasm_arm64.h(191): warning C4146: unary minus operator applied to unsigned type, result still unsigned
.\../dynasm/dasm_arm64.h(247): warning C4244: '=': conversion from '__int64' to 'int', possible loss of data
... same warning at different line ...
.\../dynasm/dasm_arm64.h(317): warning C4244: '=': conversion from '__int64' to 'int', possible loss of data
.\../dynasm/dasm_arm64.h(429): warning C4244: 'return': conversion from '__int64' to 'int', possible loss of data
... same warning at different line ...
.\../dynasm/dasm_arm64.h(447): warning C4244: 'return': conversion from '__int64' to 'int', possible loss of data
.\../dynasm/dasm_arm64.h(515): warning C4244: '=': conversion from '__int64' to 'int', possible loss of data
C:\Users\MikuAuahDark\personal-lua-stuff\LuaJIT\src\host\buildvm_arch.h(5823): warning C4146: unary minus operator applied to unsigned type, result still unsigned
... same warning at different line ...
C:\Users\MikuAuahDark\personal-lua-stuff\LuaJIT\src\host\buildvm_arch.h(6494): warning C4146: unary minus operator applied to unsigned type, result still unsigned
buildvm_asm.c
buildvm_fold.c
buildvm_lib.c
buildvm_peobj.c
Generating Code...

*******************************************************
*** Build FAILED -- Please check the error messages ***
*******************************************************
```

Looks like MSVC doesn't like when the array size is 0. Also the PE code generator doesn't support ARM64 as stated above so even by patching those zero-sized array declaration with ifdefs, it will still fail to compile anyway.

As a side note, looks like two invocations to `VsDevCmd.bat` is required. One for setting up the host compiler and one for setting up the cross compiler, since the executable name for the host compiler and the cross compiler is both `cl.exe` which can't be distinguished. This ultimately requires "Developer Command Prompt" to be used.

I'm not sure how useful this information, but I think comment above states pretty much everything what's needed to make LuaJIT compile or working with Windows/ARM64 combintiation.

**Comment by tommyvct** [comment]
I'm also trying to port obs-studio to Windows arm64. They use LuaJIT as one of their scripting engine. 
As @MikuAuahDark mentioned, 2 invocations to `VsDevCmd.bat` is indeed required.

I ended up splitting `msvcbuild.bat` into 2 parts. The First part using the x64 native toolchain, compiles the helper program, then the second part uses x64-arm64 toolchain to cross-compiles to ARM64 PE binaries.

I met quite a few obstacles and here's my attempt to make it work:
1. LuaJIT-2.0.5\src\lj_arch.h(55): fatal error C1189: #error:  "No support for this architecture (yet)"
This happens because msvc toolchain use `_M_ARM` and `_M_ARM64` to indicate ARM/64 architectures. I patched it up then this comes up:
2. LuaJIT-2.0.5\src\lj_arch.h(336): fatal error C1189: #error:  "Only ARM EABI or iOS 3.0+ ABI is supported"
I commented that check out then this comes up:
3. LuaJIT-2.0.5\src\lj_ircall.h(256): fatal error C1189: #error:  "Missing fp64 helper definitions for this compiler"
At this point I realized that that part of code is only for GCC, as these fp64 symbols are nowhere to be found in msvc toolchain.

**Comment by MikePall** [comment]
LuaJIT 2.0 doesn't have support for ARM64. You need to start with LuaJIT 2.1 git.

**Comment by stuta** [comment]
I'm using msys2\clangarm64 added by pacman -S mingw-w64-clang-aarch64-toolchain (see https://github.com/msys2/MSYS2-packages/issues/1787).

When I run ` mingw32-make CFLAGS="-DLUAJIT_ENABLE_LUA52COMPAT"` I get `Error: no PE object support for this target`. Is it possible to build to Windows arm64 with any flags?

**Comment by MikuAuahDark** [comment]
I don't think so. There seems to be no progress on this. See https://github.com/LuaJIT/LuaJIT/issues/593#issuecomment-649235956 for the blockers.

**Comment by YangYang129** [comment]
LuaJIT failed to build "This version of F:\LuaJIT\src\minilua.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher." with MSVC on windows ARM64. It can reproduces on latest version https://github.com/LuaJIT/LuaJIT/commit/c4fe76d50cda24f3529604448f80ff14754599dd of branch 2.1.
**Environment**
Compiler version: VS2019 (16.11.9)
Operating system: Windows server 2019
**Steps to reproduce:**
1. open VS2019 x64 tools command
2. git clone https://github.com/LuaJIT/LuaJIT F:\LuaJIT
3.. cd F:\LuaJIT\src
4. "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\VsDevCmd.bat" -host_arch=amd64 -arch=arm64
5. Replace "x64" to "arm64" in msvcbuild.bat fold
6. msvcbuild.bat
**Error log:**
![image](https://user-images.githubusercontent.com/86757616/158925592-8e49e4ec-6b4f-422c-9c8a-33eebcd676a1.png)
This version of F:\LuaJIT\src\minilua.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.

**Comment by MikuAuahDark** [comment]
You must use the host (x64) compiler to get at least minilua working (or compile LuaJIT for x64 then let it uses your host LuaJIT) then somewhere in the middle switch to ARM64 cross compiler.

**Comment by YangYang129** [comment]
@roymacdonald Thank you for your info. According to your description. I think step as follow:
1. open VS2019 x64 tools command
2. git clone https://github.com/LuaJIT/LuaJIT F:\LuaJIT
3. cd F:\LuaJIT\src
4. msvcbuild.bat
should can generate minilua.exe on x64, but then I don't understand what mean "somewhere in the middle switch to ARM64 cross compiler.". Can you help me with the relevant compilation commands? Thank you very much

**Comment by tommyvct** [comment]
Spoiler herez even if you did get minilua to work, you still can't compile LuaJIT because there are multiple header guards that will `#error` out the compilation.

**Comment by YangYang129** [comment]
@tommyvct Thank you for your investigation. According to your description, LuaJIT project doesn't have support for ARM64 WINDOWS for now. Is it?

**Comment by tommyvct** [comment]
> Current holes I observed:
> 
> * [ ]  The PE code generator should be modified to support ARM64.
> * [ ]  ARM64 SEH needs to be implemented.
> * [ ]  Fix the build system to allow cross compilation.
> 
> CC @imbushuo

According to this, not yet. I might be wrong because I haven't been in this for quite a while.

Depending on what do want, there is a way of getting it to work:

Compile to your host program to [ARM64EC](https://blogs.windows.com/windowsdeveloper/2021/06/28/announcing-arm64ec-building-native-and-interoperable-apps-for-windows-11-on-arm/), then link to X64 build of LuaJIT.

TL; DR: ARM64EC is a new MSVC toolchain that behaves like a normal X64 toolchain but instead it compiles to ARM64 code instead. It also allows binary interop between ARM64 and X64 binaries. 

The pros are its still ARM64 code and have not perfect but pretty amazing binary compatibility with X64 libs, either statically or dynamically. In most of the cases if that program can compile into X64 binaries then you can compile to ARM64EC without the need to modify any code, it just compiles and runs.

The cons are for ARM64EC, SIMD operations like SSE and AVX are emulated by software and not translated to NEON, so if your software have a lot of these operations then it could be a performance bottleneck. Also, the ARM64EC toolchain is still experimental, it could be painful to use or doesn't work with you program at all.

**Comment by Myriachan** [comment]
One thing I see that needs to be done is `lj_mcode_sync` needs to call `FlushInstructionCache` if on non-x86 Windows.

**Comment by hmartinez82** [comment]
I have a Surface Pro X and I'm able to start compiling LuaJIT in MSYS2 using Clang. 
@tommyvct The small change  to the Makefile was a singel line, the issue now are those 3 holes you meant. I'm hitting the first one. 
Unfortunately PE Headers are totally out of my league :( 
This is the line where compilation fails 
https://github.com/LuaJIT/LuaJIT/blob/v2.1/src/host/buildvm_peobj.c#L375

**Comment by mgood7123** [comment]
does this ALSO apply for `Android aarch64` ?

as i cant seem to get https://luajit.org/install.html#android to work

**Comment by stephenjust** [comment]
I've been playing around with implementing this but have hit some issues as I reach the limits of my knowledge:
https://github.com/stephenjust/LuaJIT/commit/9c7dbda52ac74ee155136c494382de01e0a41c4e

This will build with msys2 clangarm64 or MSVC 2022 ARM native tools. (Presumably cross tools as well, but I'm running native.)

Things of note:

* MSVC compiler bug triggered by lj_ir.c, passing /Oi- to the compiler works around the issue. I don't see this issue for other compiler architectures.
* I don't know how to implement the SEH part.
* I'm hitting a weird issue where the version of vm_arm64.dasc processed by dynasm has an infinite loop in vm_growstack_l, L438 seems to point back to itself when running the output in a debugger.

```
> ./luajit -e 'print("foo")'
foo
```

```
> ./luajit -e 'print(require("lgi")._VERSION)'
... triggers infinite loop, connect a debugger and step into function ...
```

![image](https://user-images.githubusercontent.com/3144757/220225940-18e30de4-cd4a-41ce-9e07-197505b45d3e.png)

(According to vm_arm64.dasc, it should be jumping to `lj_state_growstack`.)

**Comment by MikePall** [comment]
Initial support for a native ARM64 Visual Studio build has been added. Untested, since I'm lacking the target environment. But hopefully not too far off.

TODO:
- [ ] Test MinGW Windows/ARM64 native build
- [ ] Test MinGW Windows/x64 -> Windows/ARM64 cross build
- [ ] Test MinGW Linux/x64 -> Windows/ARM64 cross build
- [ ] Add support for VC++ Windows/x64 -> Windows/ARM64 cross build
- [ ] Update install docs and status page

**Comment by corsix** [comment]
> MSVC compiler bug triggered by lj_ir.c, passing /Oi- to the compiler works around the issue. I don't see this issue for other compiler architectures.

This issue seems present with Mike's commit. There's a decent write-up at https://sqlite.org/forum/info/45a55d06c14bed82?t=h, the TLDR of which seems to be that an MSVC bug prevents taking the address of `floor` or `ceil`. The `lj_ir_callinfo` initialiser takes the address of `lj_vm_floor` and `lj_vm_ceil`, which lj_vm.h defines as aliases of `floor` and `ceil` if `LJ_TARGET_PPC || LJ_TARGET_ARM64 || (LJ_TARGET_MIPS && LJ_ABI_SOFTFP)`. I think we can sidestep the issue by making a tweak elsewhere, noting that `lj_asm_arm64.h:asm_fpmath` handles all the relevant functions via `asm_fpunary` rather than `asm_callid`:
```diff
diff --git a/src/lj_ircall.h b/src/lj_ircall.h
index 569134e985..f342cdd2f9 100644
--- a/src/lj_ircall.h
+++ b/src/lj_ircall.h
@@ -63,7 +63,7 @@ typedef struct CCallInfo {
 /* Helpers for conditional function definitions. */
 #define IRCALLCOND_ANY(x)              x
 
-#if LJ_TARGET_X86ORX64
+#if LJ_TARGET_X86ORX64 || LJ_TARGET_ARM64
 #define IRCALLCOND_FPMATH(x)           NULL
 #else
 #define IRCALLCOND_FPMATH(x)           x
```

---

We're hitting `#error "NYI: ARM64 Windows ABI calling conventions"` in lj_crecord.c, which can be temporarily commented out, but I know there's going to be an issue around calls to vararg functions (both interpreter and JIT).

---

More pressing is that unwind currently fails horribly (we call KernelBase.dll!RaiseException, which ends up segfaulting in  	ntdll.dll!RtlpUnwindRestoreRegisterRange). I am investigating.

**Comment by corsix** [comment]
Unwinding part 1: the `.xdata` section should describe the actions of prolog (e.g. alloc_s / add_fp / save_*), but in the order of the epilog. Ideally there'd also be a 1:1:1 correspondence between unwind actions and instructions in the epilog and (in reverse) instructions in the prolog, as (with some extra effort) this would make it possible to unwind in prologs and epilogs, but we don't seem to aim for that. IOW, we're describing the actions of a hypothetical epilog, in epilog order, but phrasing each action in prolog terms.

The main `restoreregs` restores GPRs and FPRs, then restores FP+LR, then adds CFRAME_SPACE to SP. Unwind codes should describe this. Notably, we don't need a CADD_FP action, as while `saveregs` constructs `fp` from `sp`, `restoreregs` doesn't restore `sp` from `fp`.

The tail of `vm_ffi_call` restores `sp` from `fp`, then restores FP+LR, then restores x20+x19. The complication is that x20+x19 is the wrong order for an unwind code pair, so we need to describe it as two separate restorations rather than a combined pair restoration, and only the latter of these restorations wants to be a save_regx.

```diff
diff --git a/src/host/buildvm_peobj.c b/src/host/buildvm_peobj.c
index e3e1026ee1..6e90a02c26 100644
--- a/src/host/buildvm_peobj.c
+++ b/src/host/buildvm_peobj.c
@@ -362,6 +362,7 @@ void emit_peobj(BuildCtx *ctx)
 #define CSAVE_FREGS(r1,r2,o1) do { \
   int r, o; for (r = r1, o = o1; r <= r2; r += 2, o -= 16) CSAVE_FREGP(r, o); \
 } while (0)
+#define CSAVE_REG(r,o) CBE16(0xd000 | (((r) - 19) << 6) | ((o) >> 3))
 #define CSAVE_REGX(r,o)        CBE16(0xd400 | (((r) - 19) << 5) | (~(o) >> 3))
 #define CADD_FP(s)     CBE16(0xe200 | ((s) >> 3))  /* s < 8*256 */
 #define CODE_NOP       0xe3
@@ -373,12 +374,11 @@ void emit_peobj(BuildCtx *ctx)
 
     /* Unwind codes for .text section with handler. */
     p = uwc;
-    CALLOC_S(208);             /* +1 */
-    CSAVE_FPLR(192);           /* +1 */
-    CADD_FP(192);              /* +2 */
     CSAVE_REGS(19, 28, 184);   /* +5*2 */
     CSAVE_FREGS(8, 15, 104);   /* +4*2 */
-    CEND_ALIGN;                        /* +1 +1 -> 24 */
+    CSAVE_FPLR(192);           /* +1 */
+    CALLOC_S(208);             /* +1 */
+    CEND_ALIGN;                        /* +1 +3 -> 24 */
 
     u32 = ((24u >> 2) << 27) | (1u << 20) | (fcofs >> 2);
     owrite(ctx, &u32, 4);
@@ -389,9 +389,9 @@ void emit_peobj(BuildCtx *ctx)
 
     /* Unwind codes for vm_ffi_call without handler. */
     p = uwc;
-    CSAVE_FPLR(16);            /* +1 */
     CADD_FP(16);               /* +2 */
-    CSAVE_REGX(19, -24);       /* +2 */
+    CSAVE_FPLR(16);            /* +1 */
+    CSAVE_REG(19, 8);          /* +2 */
     CSAVE_REGX(20, -32);       /* +2 */
     CEND_ALIGN;                        /* +1 +0 -> 8 */
```

Unwinding part 2: it looks like the `f` we get in `lj_err_unwind_win` is _after_ all the unwind actions have been performed, so we need to undo one step to get `cf`:
```diff
diff --git a/src/lj_err.c b/src/lj_err.c
index 6e50cbee3b..16898ac589 100644
--- a/src/lj_err.c
+++ b/src/lj_err.c
@@ -261,6 +261,8 @@ LJ_FUNCA int lj_err_unwind_win(EXCEPTION_RECORD *rec,
 {
 #if LJ_TARGET_X86
   void *cf = (char *)f - CFRAME_OFS_SEH;
+#elif LJ_TARGET_ARM64
+  void *cf = (char *)f - CFRAME_SIZE;
 #else
   void *cf = f;
 #endif
@@ -299,7 +301,7 @@ LJ_FUNCA int lj_err_unwind_win(EXCEPTION_RECORD *rec,
       ** (including ourselves) again with EH_UNWINDING set. Then set
       ** stack pointer = cf, result = errcode and jump to the specified target.
       */
-      RtlUnwindEx(cf, (void *)((cframe_unwind_ff(cf2) && errcode != LUA_YIELD) ?
+      RtlUnwindEx(f, (void *)((cframe_unwind_ff(cf2) && errcode != LUA_YIELD) ?
                               lj_vm_unwind_ff_eh :
                               lj_vm_unwind_c_eh),
                  rec, (void *)(uintptr_t)errcode, ctx, dispatch->HistoryTable);
```

**Comment by corsix** [comment]
For FFI function calls, see https://github.com/corsix/LuaJIT/commits/arm64-win-vararg. The ugly part is the interpreter, as https://learn.microsoft.com/en-us/cpp/build/arm64-windows-abi-conventions isn't kidding when it says "allocate arguments to an imaginary stack, where the first 64 bytes of the stack are loaded into x0-x7, and any remaining stack arguments are placed normally" -- a function taking 7 64-bit args and then a 16-byte structure will have half the structure in GPRs and half on the stack.

**Comment by vanc** [comment]
Thanks Mike and Peter for the great work!

So far, the port is mostly working based on my testing. One thing doesn't work is the external exception handling. If a C++ library throws an exception inside a xpcall, LuaJIT will segment fault. It works fine on arm64 Linux target.

**Comment by MikePall** [comment]
I think the unwind codes for `lj_vm_ffi_call` still aren't fully correct.

**Comment by corsix** [comment]
It makes no difference in my very simple test case, but it looks like `#define CSAVE_REG` gained a `~` between my post above and what ended up in git (I think it wants to be without a ~, like CSAVE_REGP, rather than with a ~, like CSAVE_REGX).

**Comment by MikePall** [comment]
Fixed. Sorry.

**Comment by vanc** [comment]
The latest fix doesn't seem to solve the external exception issue.

**Comment by vanc** [comment]
Sorry Peter. I didn't make myself clear. I was actually running the [LuaJIT test suite](https://github.com/openresty/luajit2-test-suite) with the [catch_cpp test](https://github.com/openresty/luajit2-test-suite/blob/master/test/sysdep/catch_cpp.lua).

It should be scenario 1. No FFI is in-use.

**Comment by corsix** [comment]
With a debugger attached, the `RtlUnwindEx` call in `lj_err_unwind_win` is failing with "Unhandled exception at 0x00007FF8167CB250 (ntdll.dll) in luajit.exe: 0xC00000FF: A malformed function table was encountered during an unwind operation." This is separate to the issue raised by @vanc, but is something I ran into while trying to debug said issue. One theory I had is that _our_ function tables are malformed, but that an error about this malformedness was suppressed unless a debugger was attached. This theory turned out to be false; our tables might or might not be malformed, but the 0xC00000FF error wasn't about our tables, as the error was raised when trying to unwind the frame for `ntdll.dll!KiUserExceptionDispatch`, well before any of our functions were looked at for unwinding. The question is why unwinding this frame is problematic with a debugger attached, but fine without a debugger attached. The answer to that question is that said frame _only exists if a debugger is attached_; without a debugger attached, executing `error('x')` results in a call stack like:
```
lua51.dll!lj_err_unwind_win
ntdll.dll!RtlpExecuteHandlerForException
ntdll.dll!RtlDispatchException
ntdll.dll!RtlRaiseException  // Note
KernelBase.dll!RaiseException
lua51.dll!err_raise_ext
lua51.dll!lj_err_throw
lua51.dll!lj_err_run
lua51.dll!lua_error
lua51.dll!lj_cf_error
```
Whereas with a debugger attached, there's a `KiUserExceptionDispatch` frame instead of a `RtlRaiseException` frame:
```
lua51.dll!lj_err_unwind_win
ntdll.dll!RtlpExecuteHandlerForException
ntdll.dll!RtlDispatchException
ntdll.dll!KiUserExceptionDispatch  // Note
KernelBase.dll!RaiseException
lua51.dll!err_raise_ext
lua51.dll!lj_err_throw
lua51.dll!lj_err_run
lua51.dll!lua_error
lua51.dll!lj_cf_error
```
This is a deliberate feature of `RtlRaiseException`; the implementation is [along the lines of](https://doxygen.reactos.org/d6/dea/sdk_2lib_2rtl_2amd64_2except_8c_source.html#l00018): declare a local a variable `CONTEXT context;`, populate said variable via `RtlCaptureContext(&context);`, then either call `RtlDispatchException` (if no debugger present) or `NtRaiseException` (if debugger present), in either case passing along the `PEXCEPTION_RECORD` we started with plus the `PCONTEXT` we just created. The implementation of `NtRaiseException` is `svc 0x172; ret;` (at least in the `ntdll.dll` I'm looking at right now; Windows system call numbers are famously unstable).

The implementation of `KiUserExceptionDispatcher` is something like:
```c
void KiUserExceptionDispatcher() {
    CONTEXT ContextRecord; // At SP+0
    EXCEPTION_RECORD ExceptionRecord; // At SP+0x390
after_svc:
    if (Wow64PrepareForException) Wow64PrepareForException(&ExceptionRecord, &ContextRecord);
    RtlDispatchException(&ExceptionRecord, &ContextRecord);
    ...
```

When `NtRaiseException` re-emerges out of kernel mode, it is into `KiUserExceptionDispatcher`; PC is set to `after_svc`, and a stack frame for `KiUserExceptionDispatcher` is _created by the kernel_, with the `ContextRecord` and `ExceptionRecord` local variables initialised using the values passed to `NtRaiseException`. Of particular note is that `ContextRecord` and `ExceptionRecord` are full-sized variables here, containing copies of what was passed to `NtRaiseException` (modulo any funging done in kernel-mode), rather than being the original pointers passed to `NtRaiseException`.

Also of note are the unwind actions for `KiUserExceptionDispatcher`, which are:
```
0xEA (MSFT_OP_CONTEXT)
0xE4 (ret)
```
This `MSFT_OP_CONTEXT` action is special; [MSDN](https://learn.microsoft.com/en-us/cpp/build/arm64-exception-handling?view=msvc-170) documents its existence, but provides no details, meanwhile [Wine](https://github.com/Tk-Glitch/wine-tkg/blob/f5c727c8828a7713471a99e836b44545924f8092/dlls/ntdll/signal_arm64.c#L770) provides a plausible implementation: unwind by adopting the `CONTEXT` object at `SP` (c.f. the `At SP+0` comment above).

Moving along a step, we get to `RtlDispatchException`, either because `RtlRaiseException` called it directly, or because `KiUserExceptionDispatcher` called it. This searches the stack for an exception handler, and then calls said handler via `RtlpExecuteHandlerForException`. That handler is our `lj_err_unwind_win`, with four arguments: `EXCEPTION_RECORD *rec`, `void *f`, `CONTEXT *ctx`, `UndocumentedDispatcherContext *dispatch`. Without a debugger attached, `rec` will point to a local variable of `KernelBase.dll!RaiseException`, and `ctx` will point to a local variable of `ntdll.dll!RtlRaiseException`. _With_ a debugger attached, `rec` and `ctx` will point to the local variables of `KiUserExceptionDispatcher`. In either case, `dispatch` will point to a local variable of `RtlDispatchException`, and `f` will be `dispatch->EstablisherFrame`. Assuming it finds a suitable `pcall` frame, `lj_err_unwind_win` will call `RtlUnwindEx` rather than returning to `RtlDispatchException` with `ExceptionContinueSearch`.

At this point, a few words about `RtlUnwind`/`RtlUnwindEx`. The implementation of `RtlUnwind` is basically:
```c
void RtlUnwind(ARGS) {
    CONTEXT context; // NB: Not even initialised
    RtlUnwindEx(ARGS, &context, (UNWIND_HISTORY_TABLE*)NULL);
}
```
Meanwhile, the implementation of `RtlUnwindEx` does an immediate `RtlCaptureContext` call using the passed `PCONTEXT` (which is why `RtlUnwind` doesn't need to initialise it), and then proceeds to unwind one frame at time (mutating the passed `PCONTEXT`) until it finds the desired stop frame. Of note is that the `PCONTEXT` going to `RtlUnwindEx` is documented as an `_In` parameter, but is actually an `_Out` parameter.

When `lj_err_unwind_win` calls `RtlUnwindEx`, it needs to pass _some_ `PCONTEXT`. You might think that it doesn't really matter _which_ `PCONTEXT` is passed, so long as we don't mind the contents of that `CONTEXT` being trashed during the unwind process. However, if you've been following carefully, you'll spot a potential problem: if there's a debugger attached, then we really don't want to pass along the `CONTEXT` sitting in `KiUserExceptionDispatcher`, as we need that `CONTEXT` in order to unwind through `KiUserExceptionDispatcher` (if there's no debugger attached, then passing along the `CONTEXT` from `ntdll.dll!RtlRaiseException` is fine, as `ntdll.dll!RtlRaiseException` doesn't have a `MSFT_OP_CONTEXT` unwind action). If we do pass along the `CONTEXT` from `KiUserExceptionDispatcher`, then by the time we come to unwind through `KiUserExceptionDispatcher`, the `CONTEXT` in `KiUserExceptionDispatcher` will describe the result of unwinding _to_ `KiUserExceptionDispatcher` rather than describing the frame underneath `KiUserExceptionDispatcher`. This rightfully upsets `RtlUnwindEx`, causing 0xC00000FF.

We therefore need to consider the question of what `PCONTEXT` should be passed to `RtlUnwindEx` by `lj_err_unwind_win`, with three obvious options:
1. Allocate a `CONTEXT` local variable, and pass it (like `RtlUnwind`).
2. Pass along the `ctx` we received as an argument (current behaviour).
3. Pass along `dispatch->ContextRecord`, i.e. the temporary `CONTEXT` that `RtlDispatchException` was using to unwind the stack as part of searching for an exception handler.

Option 1 is always safe, albeit a `CONTEXT` is relatively large, so other options are preferable if possible. Option 2 is not correct on ARM64 when a debugger is attached. Option 3 seemingly is correct on ARM64, and matches what MSVC's `__C_specific_handler` does. I would like to think that option 3 is also safe on x64, but I've not tested it.

Bonus addendum: `RtlUnwindEx` will call back into `lj_err_unwind_win`, this time with the `EH_UNWINDING` flag set. When it does so, `ctx` and `dispatch->ContextRecord` will point to the same thing. However, at this point, `lj_err_unwind_win` doesn't need to think about `CONTEXT` objects at all, as all it needs is `f`.

TLDR: At least for ARM64, and possibly for x64 too, when `lj_err_unwind_win` calls `RtlUnwindEx`, it should pass `dispatch->ContextRecord` instead of `ctx`.

**Comment by pbo-linaro** [comment]
Thanks for all the hard work you're doing here!

If you lack windows-arm64 hardware, you can try to use Linaro docker image for emulating it on linux-x64 (it uses qemu-user + wine-arm64). Some technical details are available [here](https://www.linaro.org/blog/emulate-windows-on-arm/).

In short:
```
# compile on windows machine and export LuaJIT folder, then, from linux-x64:
$ file LuaJIT/src/*.{exe,dll}
LuaJIT/src/luajit.exe: PE32+ executable (console) Aarch64, for MS Windows, 5 sections
LuaJIT/src/lua51.dll:  PE32+ executable (DLL) (GUI) Aarch64, for MS Windows, 5 sections
$ docker run -it --rm -v $(pwd)/LuaJIT:/luajit linaro/wine-arm64 wine-arm64  /luajit/src/luajit.exe -e 'print("hello world")'
hello world
```

I don't have any technical knowledge on SEH support, but you can use `WINEDEBUG=+seh wine-arm64 luajit.exe <your_test>` to get some unwinding information.

I could run some tests from [LuaJIT test suite](https://github.com/openresty/luajit2-test-suite), including the failing [catch_cpp test](https://github.com/openresty/luajit2-test-suite/blob/master/test/sysdep/catch_cpp.lua) mentioned above, which is crashing too.

Not sure if LuaJIT has an official CI somewhere (didn't find it), but this docker image can be a great solution if you already have a linux-x64 machine setup for this.

---

If you already have an arm64 (Apple silicon or Linux) machine available, those [instructions](https://linaro.atlassian.net/wiki/spaces/WOAR/pages/28914909194/windows-arm64+VM+using+qemu-system) can help you to get a windows-arm64 vm. Don't forget to add -accel kvm, or hvf (on MacOS) to get benefit from hardware acceleration.

---

Hope this can help you :+1:

**Comment by vanc** [comment]
Thanks Peter for the detailed analysis.

```
TLDR: At least for ARM64, and possibly for x64 too, when lj_err_unwind_win calls RtlUnwindEx, it should pass dispatch->ContextRecord instead of ctx.
```

Unfortunately, tried that and the `catch_cpp` test still causing segment fault.

**Comment by corsix** [comment]
Indeed, per my "this is separate to the issue raised by @vanc" I wasn't expecting it to fix things; it instead fixes something else (namely, the ability to debug things).

**Comment by corsix** [comment]
Whereas https://github.com/corsix/LuaJIT/commits/arm64-win-unwind should be more likely to fix things, as it addresses my earlier "the pair unwind codes (used for main .text section) look wrong" remark. c03d52e8e is the main event, e7dedc62 is the fix for debuggability, 94f9680a is an unrelated fix while in the area, and dd2dbdd is optional extra spicyness (on balance, probably too spicy).

**Comment by vanc** [comment]
Thanks Peter. However, the external exception issue is not completely fixed. But the behavior improved. Instead of a simple crash/segment fault, now LuaJIT threw a PANIC.

```
PANIC: unprotected error in call to Lua API (C++ exception)
```

**Comment by vanc** [comment]
That's from running the same [catch_cpp.lua](https://github.com/openresty/luajit2-test-suite/blob/master/test/sysdep/catch_cpp.lua).

**Comment by vanc** [comment]
Interestingly, Peter's arm64-win-unwind branch works with these two test cases in catch_cpp.lua.
```
do
  local a, b = pcall(function() cp.throw("foo") end)
  assert(a == false and b == "C++ exception")
end

local unwind
do
  local a, b = pcall(cp.catch, function() cp.throw("foo") end)
  unwind = a
  assert((a == false and b == "C++ exception") or (a == true and b == "foo")
    or (a == true and ffi.arch == 'arm' and b == nil))
end
```

But failed with this one:
```
do
  local a, b = pcall(cp.alloc, function()
    assert(cp.isalloc() == true)
    return "foo", cp.throw
  end)
  assert(a == false and b == "C++ exception")
  assert(cp.isalloc() == false)
end
```

This particular case uses `pcall` to invoke the C++ function `ct_alloc` from cpptest.cpp. The function calls the Lua function passed as the second parameter and receives the `ct_throw` C++ function as a result. It then invokes the function to throw a C++ exception.

**Comment by corsix** [comment]
That particular case works for me when compiling the C++ library with `/EHa`. I'd like if it worked with `/EHs` or `/EHsc` too, but when MSVC's `__InternalCxxFrameHandler<__FrameHandler3>` runs for the C++ frame in question (and it _does_ run), it seems to decide not to run any destructors.

**Comment by corsix** [comment]
This is seemingly the x64 behaviour too, based on this comment in `lj_err.c`:
```c
/*
** Apparently MSVC doesn't call C++ destructors for foreign exceptions
** unless you compile your C++ code with /EHa. Unfortunately this means
** catch (...) also catches things like access violations. The use of
** _set_se_translator doesn't really help, because it requires /EHa, too.
*/
```
It was also raised [on the mailing list last year](https://www.freelists.org/post/luajit/Windows-x64-C-exception-interoperability). As a consequence of that, the [C++ Exception Interoperability](https://luajit.org/extensions.html) page was apparently updated, though the comment about `/EHa` there is still about `catch (...)` rather than about "Throwing Lua errors across C++ frames is safe. C++ destructors will be called."

The logic in vcruntime's `__InternalCxxFrameHandler` is somewhat interesting. It'll bail out early unless one of the following cases is detected:
1. vcruntime's internal thread-local variable `cxxReThrow` is set to true.
2. The ExceptionCode is LJ_MSVC_EXCODE.
3. The ExceptionCode is STATUS_UNWIND_CONSOLIDATE, the exception has 15 parameters, and parameter 8 is EH_MAGIC_NUMBER1.
4. The ExceptionCode is STATUS_LONGJUMP.
5. The function being unwound through was compiled with `/EHa`.

This early bail-out is why it doesn't call C++ destructors for foreign exceptions (because foreign exceptions don't match cases 2/3/4).

After the early bail-out, it checks whether it is in the unwinding stage (this being `(ExceptionFlags & 0x66) != 0`, similar to our `if ((rec->ExceptionFlags & 6)) {  /* EH_UNWINDING|EH_EXIT_UNWIND */`). If so, we hit this comment:
```c
        // We're at the unwinding stage of things.  Don't care about the
        // exception itself.  (Check this first because it's easier)
```
I don't know whether the parenthesised part is an aspirational TODO saying that it should check for the unwinding stage first (because that would indeed be easier), or whether it is saying that it doesn't care about the exception but checking the exception first regardless is easier (it may well be easier, but it means it doesn't call C++ destructors for foreign exceptions). Next up, the "Don't care about the exception itself" part also becomes un-true, as there's special handling that ends up calling `FrameUnwindToState` if the ExceptionCode is STATUS_UNWIND_CONSOLIDATE or STATUS_LONGJUMP, versus calling `FrameUnwindToEmptyState` otherwise.

If we want C++ destructors to be called for Lua errors with `/EHs` or `/EHsc`, then by the time we're unwinding, we need to satisfy one of cases 1-4. Case 4 is tempting; if we could make our `RtlUnwindEx` call look like a `longjmp` call, then it should interoperate with everything neatly. Unfortunately there is all sorts of special handling in Windows' unwinder around `longjmp` (c.f. http://www.nynaeve.net/?p=106 "RtlRestoreContext will in most cases simply copy the given context into the currently active register set, although in two special cases (if a STATUS_LONGJUMP or STATUS_UNWIND_CONSOLIDATE exception code is set in the optional ExceptionRecord argument), this behavior deviates from the norm"). Case 3 is similarly associated with all sorts of special handling. That leaves case 2. If we take vcruntime's "Don't care about the exception itself" comment at its word, then matching case 2 is fairly simple: simply report the ExceptionCode as LJ_MSVC_EXCODE during the unwind process.

The quick and dirty approach is to insert this immediately before the call to `RtlUnwindEx`:
```c
      if (rec->ExceptionCode == LJ_EXCODE_MAKE(LUA_ERRRUN))
        rec->ExceptionCode = LJ_MSVC_EXCODE;
```
(this handles most cases; for cases other than `LUA_ERRRUN`, it would need a different way of communicating `errcode` to the inner `lj_err_unwind_win` call, for example stuffing it in GL)

**Comment by MikePall** [comment]
Applied. Thanks!

**Comment by corsix** [comment]
18b8fd8 (previously dd2dbdd) is indeed slightly too spicy: if we suffer an on-trace error (e.g. an on-trace call to `buffer.decode` with malformed input), then we unwind to the register state of the trace (albeit with PC repointed to a side exit stub), then end up at `vm_exit_handler`. This ends up executing `bhs >9 // Check for error from exit.`, but it does so _before_ restoring the register values of `TISNUM` / `TISNUMhi` / `TISNIL`. We then call `lj_err_trace` to re-raise the error. If that error is caught by the same interpreter frame as just raised the error, then we can end up at `vm_unwind_ff_eh` still with the on-trace values of `TISNUM` / `TISNUMhi` / `TISNIL`, and then things start to go south.

One fix is along the lines of:

```diff
   |  ldr L, SAVE_L
   |1:
   |  cmn CARG1w, #LUA_ERRERR
+  |    movz TISNUM, #(LJ_TISNUM>>1)&0xffff, lsl #48
+  |    movz TISNUMhi, #(LJ_TISNUM>>1)&0xffff, lsl #16
+  |    movn TISNIL, #0
   |  bhs >9                            // Check for error from exit.
   |   lsl RC, CARG1, #3
   |  ldr LFUNC:CARG2, [BASE, FRAME_FUNC]
-  |    movz TISNUM, #(LJ_TISNUM>>1)&0xffff, lsl #48
-  |    movz TISNUMhi, #(LJ_TISNUM>>1)&0xffff, lsl #16
-  |    movn TISNIL, #0
   |  and LFUNC:CARG2, CARG2, #LJ_GCVMASK
   |   str RCw, SAVE_MULTRES
   |   str BASE, L->base
```

(Possibly with some additional reshuffling, e.g. moving `lsl RC, CARG1, #3` to between `ldr LFUNC:CARG2` and `and LFUNC:CARG2`)

**Comment by MikePall** [comment]
Fixed. Thanks!
